name: "scheduler test - new"

on:
  schedule:
    - cron: "50 21 * * *"
    - cron: "*/9 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: |
          echo "Workflow triggered at: $(date)"
          echo "Trigger event: ${{ github.event_name }}"

      - name: Every time
        run: |
          echo "This step will always run" 
          echo "New"
